"""Batch smoke/regression reports for offline autocalibrated replay.

This tool runs ``offline_replay_autocalibrated.py`` for multiple uncalibrated
raw JSONL recordings and generates stable offline regression reports. Its role
is to help check whether the parser / adapter / TrialController /
BlockController pipeline has been broken by later code changes.

It is not a formal experiment analysis tool. Each case still uses the post-hoc
temporary task coordinate system and scene generated by
``offline_replay_autocalibrated.py``. Formal experiments still need online
calibration and formal scene configuration. The example case data is only a
placeholder; real projects should fill in paths and expectations that match
their recordings.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Sequence


SAFE_CASE_ID_PATTERN = re.compile(r"^[A-Za-z0-9_.-]+$")

SUPPORTED_CASE_ARGS = {
    "max_frames",
    "thumb_node",
    "index_node",
    "tracker_index",
    "skeleton_index",
    "up_axis",
    "calibration_mode",
    "calibration_frames",
    "scene_mode",
    "block_size",
    "track_margin",
    "track_width",
    "narrow_track_width",
    "z_tolerance",
}

CSV_COLUMNS = [
    "case_id",
    "description",
    "raw_jsonl",
    "status",
    "error_message",
    "total_raw_frames",
    "replayed_raw_frames",
    "valid_input_frames",
    "valid_pinch_frames",
    "tracker_fallback_frame_count",
    "invalid_input_frame_count",
    "moving_frame_count",
    "generated_contact_enter_count",
    "generated_contact_exit_count",
    "slip_active_frame_count",
    "blocked_frame_count",
    "large_delta_frame_count",
    "tracker_invalid_frame_count",
    "pinch_distance_min",
    "pinch_distance_mean",
    "pinch_distance_max",
    "scene_mode",
    "calibration_mode",
    "calibration_frames",
    "output_dir",
]


@dataclass(frozen=True)
class BatchCase:
    """Validated case configuration."""

    case_id: str
    raw_jsonl: str
    description: str
    args: dict[str, Any]
    expectations: list[dict[str, Any]]


@dataclass(frozen=True)
class BatchRunResult:
    """Batch run payload plus process-style exit code."""

    payload: dict[str, Any]
    exit_code: int


ReplayRunner = Callable[[BatchCase, Path, str], None]


class ReplayCaseError(RuntimeError):
    """Raised when a case replay subprocess fails."""


def run_batch(
    *,
    cases_path: Path,
    out_dir: Path,
    stop_on_fail: bool = False,
    overwrite: bool = False,
    python_executable: str = sys.executable,
    runner: ReplayRunner | None = None,
) -> BatchRunResult:
    """Run configured cases and write batch summary outputs."""

    cases = load_cases(cases_path)
    out_dir.mkdir(parents=True, exist_ok=True)
    runner = runner or run_offline_replay_subprocess

    case_results: list[dict[str, Any]] = []
    exit_code = 0
    for case in cases:
        case_out_dir = out_dir / case.case_id
        if overwrite:
            clear_case_output_dir(out_dir, case.case_id)

        result = run_case(
            case=case,
            case_out_dir=case_out_dir,
            python_executable=python_executable,
            runner=runner,
        )
        case_results.append(result)

        if stop_on_fail and result["status"] != "PASS":
            exit_code = 1
            break

    payload = build_batch_payload(case_results)
    write_batch_outputs(out_dir, payload)
    return BatchRunResult(payload=payload, exit_code=exit_code)


def run_case(
    *,
    case: BatchCase,
    case_out_dir: Path,
    python_executable: str,
    runner: ReplayRunner,
) -> dict[str, Any]:
    """Run one case and return a report row."""

    warnings: list[str] = []
    summary: dict[str, Any] = {}
    expectation_results: list[dict[str, Any]] = []
    status = "ERROR"
    error_message = ""

    try:
        runner(case, case_out_dir, python_executable)
        summary = read_case_summary(case_out_dir)
        warnings.extend(_summary_warnings(summary))
        enrich_summary_with_frame_metrics(summary, case_out_dir, warnings)
        expectation_results = evaluate_expectations(case.expectations, summary, warnings)
        status = "PASS" if all(result["passed"] for result in expectation_results) else "FAIL"
    except Exception as exc:  # Keep batch reports alive after case-level failures.
        status = "ERROR"
        error_message = str(exc)

    return {
        "case_id": case.case_id,
        "description": case.description,
        "raw_jsonl": case.raw_jsonl,
        "status": status,
        "error_message": error_message,
        "summary": summary,
        "expectation_results": expectation_results,
        "output_dir": str(case_out_dir),
        "warnings": warnings,
    }


def run_offline_replay_subprocess(
    case: BatchCase,
    case_out_dir: Path,
    python_executable: str,
) -> None:
    """Run the existing offline replay script via subprocess."""

    script_path = Path(__file__).with_name("offline_replay_autocalibrated.py")
    command = [
        python_executable,
        str(script_path),
        "--raw-jsonl",
        case.raw_jsonl,
        "--out-dir",
        str(case_out_dir),
    ]
    command.extend(case_args_to_cli(case.args))

    completed = subprocess.run(
        command,
        check=False,
        capture_output=True,
        text=True,
    )
    if completed.returncode != 0:
        message_parts = [
            f"offline replay exited with code {completed.returncode}",
            _trim_text(completed.stderr),
            _trim_text(completed.stdout),
        ]
        raise ReplayCaseError(" | ".join(part for part in message_parts if part))


def load_cases(cases_path: Path) -> list[BatchCase]:
    """Load and validate cases from JSON."""

    payload = json.loads(cases_path.read_text(encoding="utf-8"))
    raw_cases = payload.get("cases")
    if not isinstance(raw_cases, list):
        raise ValueError("cases config must contain a 'cases' list.")

    cases: list[BatchCase] = []
    seen_ids: set[str] = set()
    for index, raw_case in enumerate(raw_cases):
        if not isinstance(raw_case, dict):
            raise ValueError(f"cases[{index}] must be an object.")

        case_id = raw_case.get("id")
        if not isinstance(case_id, str):
            raise ValueError(f"cases[{index}].id must be a string.")
        validate_case_id(case_id)
        if case_id in seen_ids:
            raise ValueError(f"duplicate case id: {case_id}")
        seen_ids.add(case_id)

        raw_jsonl = raw_case.get("raw_jsonl")
        if not isinstance(raw_jsonl, str) or not raw_jsonl:
            raise ValueError(f"cases[{index}].raw_jsonl must be a non-empty string.")

        description = raw_case.get("description", "")
        if not isinstance(description, str):
            raise ValueError(f"cases[{index}].description must be a string.")

        args = raw_case.get("args", {})
        if not isinstance(args, dict):
            raise ValueError(f"cases[{index}].args must be an object.")
        unknown_args = sorted(set(args) - SUPPORTED_CASE_ARGS)
        if unknown_args:
            raise ValueError(
                f"cases[{index}].args contains unsupported keys: {', '.join(unknown_args)}"
            )

        expectations = raw_case.get("expectations", [])
        if not isinstance(expectations, list):
            raise ValueError(f"cases[{index}].expectations must be a list.")
        for expectation in expectations:
            if not isinstance(expectation, dict):
                raise ValueError(f"cases[{index}].expectations entries must be objects.")

        cases.append(
            BatchCase(
                case_id=case_id,
                raw_jsonl=raw_jsonl,
                description=description,
                args=dict(args),
                expectations=[dict(expectation) for expectation in expectations],
            )
        )
    return cases


def validate_case_id(case_id: str) -> None:
    """Reject path-like or unsafe case identifiers."""

    if case_id in {".", ".."} or not SAFE_CASE_ID_PATTERN.fullmatch(case_id):
        raise ValueError(
            "case id must contain only letters, digits, underscores, hyphens, and dots."
        )


def clear_case_output_dir(out_dir: Path, case_id: str) -> None:
    """Safely clear only the output subdirectory for one case."""

    validate_case_id(case_id)
    out_dir_resolved = out_dir.resolve()
    case_dir = (out_dir / case_id).resolve()
    if case_dir == out_dir_resolved or out_dir_resolved not in case_dir.parents:
        raise ValueError(f"refusing to clear unsafe case output directory: {case_dir}")
    if case_dir.exists():
        shutil.rmtree(case_dir)


def case_args_to_cli(args: dict[str, Any]) -> list[str]:
    """Convert supported JSON args to offline replay CLI args."""

    cli: list[str] = []
    for key, value in args.items():
        if value is None:
            continue
        if key not in SUPPORTED_CASE_ARGS:
            raise ValueError(f"unsupported case arg: {key}")
        flag = "--" + key.replace("_", "-")
        cli.extend([flag, _format_arg_value(key, value)])
    return cli


def read_case_summary(case_out_dir: Path) -> dict[str, Any]:
    """Read a case summary.json."""

    summary_path = case_out_dir / "summary.json"
    if not summary_path.exists():
        raise FileNotFoundError(f"summary.json not found in {case_out_dir}")
    payload = json.loads(summary_path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"summary.json must contain an object: {summary_path}")
    return payload


def enrich_summary_with_frame_metrics(
    summary: dict[str, Any],
    case_out_dir: Path,
    warnings: list[str],
) -> None:
    """Add batch-derived metrics that older summary.json files may not contain."""

    frames_path = case_out_dir / "frames.csv"
    if "moving_frame_count" not in summary:
        moving_count = count_moving_frames(frames_path, warnings)
        summary["moving_frame_count"] = moving_count
    if "blocked_frame_count" not in summary:
        blocked_count = count_blocked_frames(frames_path, warnings)
        summary["blocked_frame_count"] = blocked_count


def count_moving_frames(frames_path: Path, warnings: list[str]) -> int | None:
    """Count moving frames using simple string checks only."""

    rows = read_frame_rows(frames_path, warnings)
    if rows is None:
        return None
    if not rows:
        return 0

    fieldnames = set(rows[0].keys())
    if "block_motion_state" in fieldnames:
        return sum(_contains(row.get("block_motion_state"), "MOVING") for row in rows)
    if "contact_state" in fieldnames:
        return sum(_contains(row.get("contact_state"), "MOVING") for row in rows)

    warnings.append("unable to compute moving_frame_count: no motion/contact field.")
    return None


def count_blocked_frames(frames_path: Path, warnings: list[str]) -> int | None:
    """Count blocked frames using simple string checks only."""

    rows = read_frame_rows(frames_path, warnings)
    if rows is None:
        return None
    count = 0
    for row in rows:
        if (
            _contains(row.get("stop_reason"), "TRACK_BLOCKED")
            or _contains(row.get("contact_state"), "BLOCKED")
            or _contains(row.get("block_motion_state"), "BLOCKED")
        ):
            count += 1
    return count


def read_frame_rows(frames_path: Path, warnings: list[str]) -> list[dict[str, str]] | None:
    """Read frames.csv if available."""

    if not frames_path.exists():
        warnings.append(f"unable to read frames.csv for derived metrics: {frames_path}")
        return None
    with frames_path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def evaluate_expectations(
    expectations: list[dict[str, Any]],
    summary: dict[str, Any],
    warnings: list[str],
) -> list[dict[str, Any]]:
    """Evaluate expectation checks against the summary metrics."""

    results: list[dict[str, Any]] = []
    for expectation in expectations:
        metric = expectation.get("metric")
        op = expectation.get("op")
        expected = expectation.get("value")
        actual = summary.get(metric) if isinstance(metric, str) else None
        missing_metric = not isinstance(metric, str) or metric not in summary
        passed = False
        error_message = ""

        if missing_metric:
            warnings.append(f"missing metric for expectation: {metric}")
        else:
            try:
                passed = compare_values(actual, op, expected)
            except Exception as exc:
                error_message = str(exc)

        result = {
            "metric": metric,
            "op": op,
            "expected": expected,
            "actual": actual,
            "passed": bool(passed),
        }
        if missing_metric:
            result["missing_metric"] = True
        if error_message:
            result["error_message"] = error_message
        results.append(result)
    return results


def compare_values(actual: Any, op: Any, expected: Any) -> bool:
    """Compare one actual value with one expected value."""

    if op == "==":
        return actual == expected
    if op == "!=":
        return actual != expected
    if op == ">":
        return _number(actual) > _number(expected)
    if op == ">=":
        return _number(actual) >= _number(expected)
    if op == "<":
        return _number(actual) < _number(expected)
    if op == "<=":
        return _number(actual) <= _number(expected)
    if op == "between":
        if not isinstance(expected, list | tuple) or len(expected) != 2:
            raise ValueError("between expectation value must be [min, max].")
        actual_number = _number(actual)
        return _number(expected[0]) <= actual_number <= _number(expected[1])
    raise ValueError(f"unsupported expectation op: {op}")


def build_batch_payload(case_results: list[dict[str, Any]]) -> dict[str, Any]:
    """Build the JSON summary payload."""

    return {
        "total_cases": len(case_results),
        "passed_cases": sum(result["status"] == "PASS" for result in case_results),
        "failed_cases": sum(result["status"] == "FAIL" for result in case_results),
        "error_cases": sum(result["status"] == "ERROR" for result in case_results),
        "cases": case_results,
    }


def write_batch_outputs(out_dir: Path, payload: dict[str, Any]) -> None:
    """Write batch_summary.csv and batch_summary.json."""

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "batch_summary.json").write_text(
        json.dumps(payload, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    with (out_dir / "batch_summary.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=CSV_COLUMNS)
        writer.writeheader()
        for result in payload["cases"]:
            writer.writerow(case_result_to_csv_row(result))


def case_result_to_csv_row(result: dict[str, Any]) -> dict[str, Any]:
    """Flatten one case result for CSV."""

    summary = result.get("summary") or {}
    row = {
        "case_id": result.get("case_id"),
        "description": result.get("description"),
        "raw_jsonl": result.get("raw_jsonl"),
        "status": result.get("status"),
        "error_message": result.get("error_message"),
        "output_dir": result.get("output_dir"),
    }
    for column in CSV_COLUMNS:
        if column not in row:
            row[column] = summary.get(column)
    return {key: _csv_value(value) for key, value in row.items()}


def _summary_warnings(summary: dict[str, Any]) -> list[str]:
    warnings = summary.get("warnings", [])
    if warnings is None:
        return []
    if isinstance(warnings, list):
        return [str(warning) for warning in warnings]
    return [str(warnings)]


def _format_arg_value(key: str, value: Any) -> str:
    if key == "up_axis" and isinstance(value, list | tuple):
        return ",".join(str(part) for part in value)
    return str(value)


def _contains(value: Any, needle: str) -> bool:
    return needle in str(value or "").upper()


def _number(value: Any) -> float:
    if value is None or value == "":
        raise ValueError("value is not numeric.")
    return float(value)


def _trim_text(value: str | None, max_length: int = 2000) -> str:
    if not value:
        return ""
    value = value.strip()
    if len(value) <= max_length:
        return value
    return value[:max_length] + "...[truncated]"


def _csv_value(value: Any) -> Any:
    if value is None:
        return ""
    if isinstance(value, list | dict):
        return json.dumps(value, sort_keys=True)
    return value


def _parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Batch offline replay report.")
    parser.add_argument("--cases", required=True)
    parser.add_argument("--out-dir", default="data/offline_replay_batch")
    parser.add_argument("--stop-on-fail", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--python-executable", default=sys.executable)
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    """CLI entrypoint."""

    args = _parse_args(argv)
    result = run_batch(
        cases_path=Path(args.cases),
        out_dir=Path(args.out_dir),
        stop_on_fail=args.stop_on_fail,
        overwrite=args.overwrite,
        python_executable=args.python_executable,
    )
    print(json.dumps(result.payload, indent=2, sort_keys=True))
    return result.exit_code


if __name__ == "__main__":
    raise SystemExit(main())
